<?php

namespace ContainerU13wkEI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCandidateFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CandidateFormType' shared autowired service.
     *
     * @return \App\Form\CandidateFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CandidateFormType.php';

        return $container->privates['App\\Form\\CandidateFormType'] = new \App\Form\CandidateFormType();
    }
}
