<?php

namespace ContainerROzkMrM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NZC1minService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NZC1min' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NZC1min'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jobOffer' => ['privates', '.errored..service_locator.NZC1min.App\\Entity\\JobOffer', NULL, 'Cannot autowire service ".service_locator.NZC1min": it references class "App\\Entity\\JobOffer" but no such service exists.'],
        ], [
            'jobOffer' => 'App\\Entity\\JobOffer',
        ]);
    }
}
