<?php

namespace ContainerROzkMrM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C8uM3K1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c8uM3K1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c8uM3K1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jobOfferRepository' => ['privates', 'App\\Repository\\JobOfferRepository', 'getJobOfferRepositoryService', true],
        ], [
            'jobOfferRepository' => 'App\\Repository\\JobOfferRepository',
        ]);
    }
}
