<?php

namespace ContainerROzkMrM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WTzMsXHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wTzMsXH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wTzMsXH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CandidateController::delete' => ['privates', '.service_locator.7kIMc4J', 'get_ServiceLocator_7kIMc4JService', true],
            'App\\Controller\\CandidateController::edit' => ['privates', '.service_locator.7kIMc4J', 'get_ServiceLocator_7kIMc4JService', true],
            'App\\Controller\\CandidateController::index' => ['privates', '.service_locator.H4sudLU', 'get_ServiceLocator_H4sudLUService', true],
            'App\\Controller\\CandidateController::show' => ['privates', '.service_locator.7kIMc4J', 'get_ServiceLocator_7kIMc4JService', true],
            'App\\Controller\\JobOfferController::delete' => ['privates', '.service_locator.NZC1min', 'get_ServiceLocator_NZC1minService', true],
            'App\\Controller\\JobOfferController::edit' => ['privates', '.service_locator.NZC1min', 'get_ServiceLocator_NZC1minService', true],
            'App\\Controller\\JobOfferController::index' => ['privates', '.service_locator.c8uM3K1', 'get_ServiceLocator_C8uM3K1Service', true],
            'App\\Controller\\JobOfferController::show' => ['privates', '.service_locator.NZC1min', 'get_ServiceLocator_NZC1minService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.oMKXChL', 'get_ServiceLocator_OMKXChLService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CandidateController:delete' => ['privates', '.service_locator.7kIMc4J', 'get_ServiceLocator_7kIMc4JService', true],
            'App\\Controller\\CandidateController:edit' => ['privates', '.service_locator.7kIMc4J', 'get_ServiceLocator_7kIMc4JService', true],
            'App\\Controller\\CandidateController:index' => ['privates', '.service_locator.H4sudLU', 'get_ServiceLocator_H4sudLUService', true],
            'App\\Controller\\CandidateController:show' => ['privates', '.service_locator.7kIMc4J', 'get_ServiceLocator_7kIMc4JService', true],
            'App\\Controller\\JobOfferController:delete' => ['privates', '.service_locator.NZC1min', 'get_ServiceLocator_NZC1minService', true],
            'App\\Controller\\JobOfferController:edit' => ['privates', '.service_locator.NZC1min', 'get_ServiceLocator_NZC1minService', true],
            'App\\Controller\\JobOfferController:index' => ['privates', '.service_locator.c8uM3K1', 'get_ServiceLocator_C8uM3K1Service', true],
            'App\\Controller\\JobOfferController:show' => ['privates', '.service_locator.NZC1min', 'get_ServiceLocator_NZC1minService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.oMKXChL', 'get_ServiceLocator_OMKXChLService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CandidateController::delete' => '?',
            'App\\Controller\\CandidateController::edit' => '?',
            'App\\Controller\\CandidateController::index' => '?',
            'App\\Controller\\CandidateController::show' => '?',
            'App\\Controller\\JobOfferController::delete' => '?',
            'App\\Controller\\JobOfferController::edit' => '?',
            'App\\Controller\\JobOfferController::index' => '?',
            'App\\Controller\\JobOfferController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CandidateController:delete' => '?',
            'App\\Controller\\CandidateController:edit' => '?',
            'App\\Controller\\CandidateController:index' => '?',
            'App\\Controller\\CandidateController:show' => '?',
            'App\\Controller\\JobOfferController:delete' => '?',
            'App\\Controller\\JobOfferController:edit' => '?',
            'App\\Controller\\JobOfferController:index' => '?',
            'App\\Controller\\JobOfferController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
