<?php

namespace ContainerROzkMrM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobOfferService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NZC1min.App\Entity\JobOffer' shared service.
     *
     * @return \App\Entity\JobOffer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.NZC1min": it references class "App\\Entity\\JobOffer" but no such service exists.');
    }
}
