<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container319Ww1J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container319Ww1J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container319Ww1J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container319Ww1J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container319Ww1J\App_KernelDevDebugContainer([
    'container.build_hash' => '319Ww1J',
    'container.build_id' => 'bd923b9a',
    'container.build_time' => 1594996979,
], __DIR__.\DIRECTORY_SEPARATOR.'Container319Ww1J');
