<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI7ruftc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI7ruftc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI7ruftc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI7ruftc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI7ruftc\App_KernelDevDebugContainer([
    'container.build_hash' => 'I7ruftc',
    'container.build_id' => 'd69fd145',
    'container.build_time' => 1594905577,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI7ruftc');
