<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerROzkMrM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerROzkMrM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerROzkMrM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerROzkMrM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerROzkMrM\App_KernelDevDebugContainer([
    'container.build_hash' => 'ROzkMrM',
    'container.build_id' => 'e16fcc68',
    'container.build_time' => 1595237309,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerROzkMrM');
